# -*- coding: utf-8 -*-
#
#  CocoaWrapper.py
#  AutoDMG
#
#  Created by Per Olofsson on 2017-02-14.
#  Copyright (c) 2017 Per Olofsson, University of Gothenburg. All rights reserved.
#


"""Selectively import Cocoa symbols to speed up app launch."""


from Foundation import (
    CAMediaTimingFunction,
    CFURLCreateBookmarkDataFromAliasRecord,
    CFURLCreateByResolvingBookmarkData,
    kCFAllocatorDefault,
    kCFBookmarkResolutionWithoutUIMask,
    NSApplicationSupportDirectory,
    NSAttributedString,
    NSBundle,
    NSData,
    NSDate,
    NSDateFormatter,
    NSDateFormatterLongStyle,
    NSDefaultRunLoopMode,
    NSDictionary,
    NSErrorFailingURLStringKey,
    NSFileHandle,
    NSFileHandleNotificationDataItem,
    NSFileHandleReadCompletionNotification,
    NSFileManager,
    NSIndexSet,
    NSLocale,
    NSLocaleLanguageCode,
    NSLog,
    NSMakeRange,
    NSMakeSize,
    NSMutableArray,
    NSMutableData,
    NSMutableDictionary,
    NSNotFound,
    NSNotificationCenter,
    NSObject,
    NSPipe,
    NSPropertyListBinaryFormat_v1_0,
    NSPropertyListImmutable,
    NSPropertyListSerialization,
    NSRunLoop,
    NSString,
    NSTask,
    NSTaskDidTerminateNotification,
    NSThread,
    NSTimer,
    NSURL,
    NSURLBookmarkResolutionWithoutMounting,
    NSURLBookmarkResolutionWithoutUI,
    NSURLConnection,
    NSURLRequest,
    NSURLResponseUnknownLength,
    NSUserDefaults,
    NSUserDomainMask,
    NSUserName,
    NSUTF8StringEncoding,
)

from AppKit import (
    NSAlert,
    NSAlertFirstButtonReturn,
    NSAlertSecondButtonReturn,
    NSAnimationContext,
    NSApp,
    NSApplication,
    NSBeep,
    NSBox,
    NSColor,
    NSCriticalAlertStyle,
    NSDocumentController,
    NSDragOperationCopy,
    NSDragOperationMove,
    NSDragOperationNone,
    NSFileHandlingPanelOKButton,
    NSFilenamesPboardType,
    NSFont,
    NSFontAttributeName,
    NSForegroundColorAttributeName,
    NSImage,
    NSImageView,
    NSOffState,
    NSOnState,
    NSOpenPanel,
    NSSavePanel,
    NSStringDrawingUsesLineFragmentOrigin,
    NSTableViewDropOn,
    NSTerminateCancel,
    NSTerminateNow,
    NSTextField,
    NSViewBoundsDidChangeNotification,
    NSWorkspace,
)
